configs/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("formapp.urls"))
]

formapp/urls.py
#path ni import qilamiz
from django.urls import path

#biz yozgan vievlarni import qilamiz
from .views import HomeView, SuccessView

#viewlarni nom ostida urlga ulaymiz
urlpatterns = [
    path("", HomeView, name="home"),
    path("success/", SuccessView, name="success")
]

formapp/models.py
from django.db import models

# Create your models here.
class Ruyxat(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    tell = models.CharField(max_length=13, null=True)
    #bazaga qo'shilgan ma'lumot vaqtini saqlab boruvchi ustun o'zgarmas
    add_time = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    

formapp/views.py
from django.shortcuts import render, redirect
from .form import RuyxatForm


# Create your views here.
def HomeView(request):
    if request.method == "POST":
        #form jo'natilgandan keyin obyekt yaratiladi
        form = RuyxatForm(request.POST)
        #form obyekti valid bo'lgani tekshiriladi
        if form.is_valid():
            #ma'lumot modelda saqlanadi
            form.save()
            #success nomli urlga yo'naltiradi
            return redirect('success')
    else:
        form = RuyxatForm()
    
    return render(request, 'home.html', {'form': form})

# Success view
def SuccessView(request):
    return render(request, 'success.html')

templates/home.html
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ro'yxatga olish</title>
    <!--bootstrapni yuklash-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!--poppins fontni yuklash-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            background-color: rgb(67, 187, 46);
        }
    </style>

</head>
<body class="container mt-5">

    <div class="m-2 text-center">
        <h1 class="text-center" >Omon shool xususiy maktabiga ro'yxatdan o'tish</h1>
    </div>
    <div class="card p-4 opacity-75 m-2 mt-4">
        <h2 class="text-center">Ism va Familiyangizni kiriting</h2>
        <form method="post">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="id_first_name" class="form-label">Ism</label>
                {{ form.first_name }}
            </div>

            <div class="mb-3">
                <label for="id_last_name" class="form-label">Familiya</label>
                {{ form.last_name }}
            </div>

            <div class="mb-3">
                <label for="id_tell" class="form-label">Telefon raqam</label>
                {{ form.tell }}
                <div class="form-text">Format: +998 90 123 45 67</div>
            </div>

            <button type="submit" class="btn btn-primary w-100">Yuborish</button>
        </form>
    </div>

</body>
</html>

templates/success.html
<!DOCTYPE html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Muvaffaqiyat</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!--poppins fontini o'rnatish-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Poppins', sans-serif;
            background-color: rgb(67, 187, 46);
        }
    </style>   
</head>
<body class="container mt-5 bg-info text-center d-flex flex-column align-items-stretch">
    <div class="alert alert-success m-1">
        <h2>Ro'yxatdan o'tdingiz!</h2>
        <p>Ism va familiyangiz muvaffaqiyatli saqlandi.</p>
        <a href="https://t.me/omonschool" class="btn btn-primary">Telegram Kanalga O'tish</a>
    </div>
</body>
</html>